# General Info
site_name: Estructura de Máquinas
site_description: Grandes Ideas en Arquitectura de Computadoras
site_author: CC-3
site_url: https://cc3-an.github.io/
copyright: Copyright &copy; 2022 CC3 AN

# Repository
edit_uri: edit/main/docs
repo_name: cc3-an/docs
repo_url: https://github.com/cc3-an/docs

# Theme Configuration
theme:
  favicon: assets/img/favicon.ico
  logo: assets/img/logo.jpg
  name: material
  language: es
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: grey
    accent: indigo
  features:
    - navigation.tabs
    - search.highlight

# Extra js files
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://github.com/cc3-an

# TOC
nav:
  - Inicio: index.md
  - Laboratorios:
      - "00: Git": labs/lab00.md
      - "01: C y GDB": labs/lab01.md
      - "02: C Avanzado": labs/lab02.md
      - "03: RISC-V": labs/lab03.md
  - Tutoriales:
      - "Autograders": tutorials/autograders.md
      - "Máquina Virtual": tutorials/install.md
